#!/bin/bash

# Motd generator for Linux terminal using bash

apt install figlet -qqq

# Get hostname
hostname=$(hostname)

# CPU usage
cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}')

# Memory usage
memory_usage=$(free -m | awk '/^Mem/{printf("%.2f%%", $3/$2*100.0)}')

# External IP
external_ip=$(curl -s https://api.ipify.org)

# External IP
user=$(whoami)

# Colouring
RED="\e[31m"
CYAN="\e[36m"
NC="\e[0m" # No Color

# Message
printf "${RED}"
figlet -f standard $hostname
echo -e "${CYAN}-----------------------------------------------------------${NC}"
echo -e "${CYAN} CPU usage:${NC} $cpu_usage"
echo -e "${CYAN} Memory usage:${NC} $memory_usage"
echo -e "${CYAN} External IP:${NC} $external_ip"
echo -e "${CYAN} System Boot:${NC} $(uptime -s) ($(uptime -p))"
echo -e "${CYAN} Users logged in:${NC} $(who | wc -l)"
echo -e "${CYAN} Welcome${NC} $user${CYAN}! "
echo -e "${CYAN}-----------------------------------------------------------${NC}"
